name: Upstream Sync

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时自动执行一次
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Sync fork
        run: gh repo sync ${{ github.repository }} -b main 
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
